name: JapanThaiExpress
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  screenshot: ^1.2.1
  share: ^2.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  carousel_slider: ^3.0.0
  flutter_svg: ^0.20.0-nullsafety.0
  #shared_preferences: ^0.5.12+2
  shared_preferences: ^2.0.5
  flutter_appavailability: ^0.0.21
  sweetalert: ^0.0.1
  #onesignal_flutter: ^2.6.2
  onesignal_flutter: ^2.6.1
  device_info: ^2.0.0
  pin_code_fields: ^6.1.0
  #http: ^0.12.2
  http: ^0.13.1
  #flutter_native_splash: ^1.0.3
  #flutter_form_builder: ^4.2.0
  flutter_form_builder: ^6.0.0
  #image_picker: ^0.6.7+22
  image_picker: ^0.7.4
  #flushbar: ^1.10.4
  qr_code_scanner: ^0.3.5
  timeline_tile: ^0.1.0
  #flutter_facebook_auth: ^3.3.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.0.6
  pull_to_refresh: ^1.6.5
  image_gallery_saver: ^1.6.9
  dio: ^4.0.0
  path_provider: ^2.0.0
  webview_flutter: ^2.0.4
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.7
  another_flushbar: ^1.10.20
  flutter_markdown: ^0.4.1
  device_apps: ^2.1.1
  permission_handler: ^8.1.1

dependency_overrides:
  intl: 0.17.0-nullsafety.2
  image: ^2.1.12
  xml: ^4.2.0
  # date_range_picker:
  #   git:
  #     url: https://github.com/LempereurBenjamin/date_range_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  image_path: "assets/icons/launcher-icon.png"
  android: true
  ios: true
    


flutter_native_splash:
  image: assets/logo.png
  color: ffffff
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/Live Recording.svg
    - assets/icons/Megaphone.svg
    - assets/icons/coins.svg
    - assets/logo.png
    - assets/success.png
    - assets/denied.png
    - assets/wanning.png
    - assets/promptpay.png
    - assets/logo_gateway_line.png
    - assets/stock.png
    - assets/o1.jpg
    - assets/o2.jpg
    - assets/o3.jpg
    - assets/o4.jpg
    - assets/o5.jpg
    - assets/o6.jpg
    - assets/o7.jpg
    - assets/o8.jpg
    - assets/pp.png
    - assets/mask2103.jpg
    - assets/amicle2103.jpg
    - assets/bhcle2103.jpg
    - assets/amiclep10.jpg
    - assets/mlkp5.jpg
    - assets/kbank.jpg
    - assets/images/card_bg.png
    - assets/images/nopic.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/send_in.png
    - assets/images/send_out.png
    - assets/images/in.png
    - assets/images/out.png
    - assets/images/line.png
    - assets/images/cat-wallet.png
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt/Prompt-Italic.ttf
          style: italic

    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
